version: "3"
services:
    web:
        build:
            context: .
            dockerfile: ./compose/web/Dockerfile
        ports:
            - "8000"
    redis:
        image: redis
        ports:
            - "6379"
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ""
        volumes:
            - "./db:/var/lib/mysql"
            - "./compose/mysql/:/etc/mysql/conf.d"
        ports:
            - "127.0.0.1:3307:3306"
