# Generated by Django 3.0.3 on 2020-03-10 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='problems_per_interview',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
