# Generated by Django 3.0.3 on 2020-03-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_backend', '0002_auto_20200310_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='failed_output',
            field=models.TextField(),
        ),
    ]
